language: swift
osx_image: xcode10.2
cache:
  bundler: true
  directories:
    - vendor/bundle
    - Pods

before_install:
  - brew update
  - brew install xcodegen
  - bundle install
  - xcodegen generate
  - bundle exec pod repo update
  - bundle exec pod install

script:
  - xcodebuild -workspace TAT.xcworkspace -scheme TAT -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - bundle exec danger

notifications:
  email: false
  slack: npc-designer:TIJP6Wix1qqtqFUqWvMjBw4U
